version: '3'

services:
  authentication-service:
    build: ./authentication-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
